import { TILE } from "./constants";
import { Entity } from "./types";

export const INITIAL_ENTITIES: Entity[] = [
  {
    id: "guide",
    x: 7,
    y: 6,
    type: "npc",
    name: "Eldrin the Sage",
    action: "profile",
    dialogue: [
      "Selamat datang di Meki Village, petualang!",
      "Gunakan WASD atau Arrow Keys untuk bergerak.",
      "Tekan E untuk berinteraksi dengan dunia.",
      "Periksalah Papan Quest di dekat sini untuk memulai petualangan pertamamu!",
      "Papan quest itu akan memberimu koin dan XP yang melimpah!"
    ],
    dialogueIndex: 0,
    dir: "down",
    moving: false,
    startX: 7,
    startY: 6,
    currPixelX: 7 * TILE,
    currPixelY: 6 * TILE,
    targetX: 7,
    targetY: 6,
    moveCooldown: 0,
  },
  {
    id: "builder",
    x: 22,
    y: 12,
    type: "npc",
    name: "Miko the Crafter",
    action: "projects",
    dialogue: [
      "Halo! Saya Miko si pembangun!",
      "Saya telah membangun banyak keajaiban digital di sini.",
      "Ingin melihat daftar proyek terbaik saya?",
    ],
    dialogueIndex: 0,
    dir: "down",
    moving: false,
    startX: 22,
    startY: 12,
    currPixelX: 22 * TILE,
    currPixelY: 12 * TILE,
    targetX: 22,
    targetY: 12,
    moveCooldown: 0,
  },
  {
    id: "archivist",
    x: 10,
    y: 22,
    type: "npc",
    name: "Lyra the Keeper",
    action: "skills",
    dialogue: [
      "Salam, pencari pengetahuan.",
      "Di sini saya menyimpan catatan kemampuan dan pengalaman sang kreator.",
      "TypeScript, React, Next.js, dan banyak lagi...",
    ],
    dialogueIndex: 0,
    dir: "down",
    moving: false,
    startX: 10,
    startY: 22,
    currPixelX: 10 * TILE,
    currPixelY: 22 * TILE,
    targetX: 10,
    targetY: 22,
    moveCooldown: 0,
  },
  {
    id: "chest1",
    x: 34,
    y: 8,
    type: "chest",
    name: "Peti Hutan",
    givesItem: "forest_key",
    dialogue: ["Kamu menemukan Forest Key! Gerbang gua kini terbuka."],
    dialogueIndex: 0,
    isOpen: false,
  },
  {
    id: "sign1",
    x: 21,
    y: 12,
    type: "sign",
    name: "Papan Desa",
    dialogue: ["Selamat datang di Meki Village!", "Eksplorasi dunia dan temukan rahasia yang tersembunyi."],
    dialogueIndex: 0,
  },
  {
    id: "shrine",
    x: 20,
    y: 3,
    type: "shrine",
    name: "Portal Suci",
    action: "contact",
    requiresItem: "glow_crystal",
    dialogue: [
      "Sebuah cahaya hangat memancar dari altar ini.",
      "Ini adalah pintu menuju dunia nyata sang kreator.",
      "Hubungi kami di sini!",
    ],
    dialogueIndex: 0,
  },
  // ── Enemies ────────────────────────────────────────────────────────────────
  // Slimes: wander acak sekitar patrolHome
  {
    id: "slime1",
    x: 31,
    y: 8,
    type: "enemy",
    name: "Slime Byte",
    hp: 3,
    maxHp: 3,
    behavior: "wander",
    speed: 0.4,
    damage: 15,
    xpReward: 10,
    attackRange: 1.3,
    patrolHomeX: 31,
    patrolHomeY: 8,
    dir: "down",
    moving: false,
    startX: 31,
    startY: 8,
    currPixelX: 31 * TILE,
    currPixelY: 8 * TILE,
    targetX: 31,
    targetY: 8,
    moveCooldown: 0,
  },
  {
    id: "slime2",
    x: 35,
    y: 9,
    type: "enemy",
    name: "Slime Byte",
    hp: 3,
    maxHp: 3,
    behavior: "wander",
    speed: 0.4,
    damage: 15,
    xpReward: 10,
    attackRange: 1.3,
    patrolHomeX: 35,
    patrolHomeY: 9,
    dir: "down",
    moving: false,
    startX: 35,
    startY: 9,
    currPixelX: 35 * TILE,
    currPixelY: 9 * TILE,
    targetX: 35,
    targetY: 9,
    moveCooldown: 0,
  },
  // Buglings: linear patrol (axis-based)
  {
    id: "bugling1",
    x: 6,
    y: 16,
    type: "enemy",
    name: "Bugling",
    hp: 2,
    maxHp: 2,
    behavior: "patrol",
    speed: 0.7,
    damage: 10,
    xpReward: 8,
    attackRange: 1.2,
    patrolAxis: "horizontal",
    patrolMin: 6,
    patrolMax: 14,
    patrolFixed: 16,
    dir: "right",
    moving: true,
    startX: 6,
    startY: 16,
    currPixelX: 6 * TILE,
    currPixelY: 16 * TILE,
    targetX: 14,
    targetY: 16,
    moveCooldown: 0,
  },
  {
    id: "bugling2",
    x: 22,
    y: 16,
    type: "enemy",
    name: "Bugling",
    hp: 2,
    maxHp: 2,
    behavior: "patrol",
    speed: 0.7,
    damage: 10,
    xpReward: 8,
    attackRange: 1.2,
    patrolAxis: "horizontal",
    patrolMin: 22,
    patrolMax: 32,
    patrolFixed: 16,
    dir: "right",
    moving: true,
    startX: 22,
    startY: 16,
    currPixelX: 22 * TILE,
    currPixelY: 16 * TILE,
    targetX: 32,
    targetY: 16,
    moveCooldown: 0,
  },
  {
    id: "bugling3",
    x: 36,
    y: 17,
    type: "enemy",
    name: "Bugling",
    hp: 2,
    maxHp: 2,
    behavior: "patrol",
    speed: 0.7,
    damage: 10,
    xpReward: 8,
    attackRange: 1.2,
    patrolAxis: "vertical",
    patrolMin: 17,
    patrolMax: 22,
    patrolFixed: 36,
    dir: "down",
    moving: true,
    startX: 36,
    startY: 17,
    currPixelX: 36 * TILE,
    currPixelY: 17 * TILE,
    targetX: 36,
    targetY: 22,
    moveCooldown: 0,
  },
  // Rock Imps: guard sekitar home, chase jika player mendekat
  {
    id: "rockimp1",
    x: 12,
    y: 4,
    type: "enemy",
    name: "Rock Imp",
    hp: 5,
    maxHp: 5,
    behavior: "guard",
    speed: 0.3,
    damage: 20,
    xpReward: 25,
    attackRange: 1.3,
    detectRadius: 4,
    chaseRadius: 6,
    patrolHomeX: 12,
    patrolHomeY: 4,
    dir: "down",
    moving: false,
    startX: 12,
    startY: 4,
    currPixelX: 12 * TILE,
    currPixelY: 4 * TILE,
    targetX: 12,
    targetY: 4,
    moveCooldown: 0,
  },
  {
    id: "rockimp2",
    x: 16,
    y: 4,
    type: "enemy",
    name: "Rock Imp",
    hp: 5,
    maxHp: 5,
    behavior: "guard",
    speed: 0.3,
    damage: 20,
    xpReward: 25,
    attackRange: 1.3,
    detectRadius: 4,
    chaseRadius: 6,
    patrolHomeX: 16,
    patrolHomeY: 4,
    dir: "down",
    moving: false,
    startX: 16,
    startY: 4,
    currPixelX: 16 * TILE,
    currPixelY: 4 * TILE,
    targetX: 16,
    targetY: 4,
    moveCooldown: 0,
  },
  // Cave Warden: mini-boss, chase agresif, radius besar
  {
    id: "cavewarden1",
    x: 9,
    y: 4,
    type: "enemy",
    name: "Cave Warden",
    hp: 15,
    maxHp: 15,
    behavior: "chase",
    speed: 0.25,
    damage: 30,
    xpReward: 80,
    attackRange: 1.5,
    detectRadius: 7,
    chaseRadius: 10,
    patrolHomeX: 9,
    patrolHomeY: 4,
    dir: "down",
    moving: false,
    startX: 9,
    startY: 4,
    currPixelX: 9 * TILE,
    currPixelY: 4 * TILE,
    targetX: 9,
    targetY: 4,
    moveCooldown: 0,
  },
  // ── Collectibles ───────────────────────────────────────────────────────────
  {
    id: "fragment1",
    x: 14,
    y: 3,
    type: "collectible",
    name: "Ancient Fragment",
    collectibleType: "ancient_fragment",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 14 * TILE,
    currPixelY: 3 * TILE,
  },
  {
    id: "fragment2",
    x: 15,
    y: 5,
    type: "collectible",
    name: "Ancient Fragment",
    collectibleType: "ancient_fragment",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 15 * TILE,
    currPixelY: 5 * TILE,
  },
  {
    id: "fragment3",
    x: 23,
    y: 13,
    type: "collectible",
    name: "Ancient Fragment",
    collectibleType: "ancient_fragment",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 23 * TILE,
    currPixelY: 13 * TILE,
  },
  {
    id: "init_stone_chip_1",
    x: 6,
    y: 5,
    type: "collectible",
    name: "Stone Chip",
    collectibleType: "stone_chip",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 6 * TILE,
    currPixelY: 5 * TILE,
  },
  {
    id: "init_stone_chip_2",
    x: 8,
    y: 8,
    type: "collectible",
    name: "Stone Chip",
    collectibleType: "stone_chip",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 8 * TILE,
    currPixelY: 8 * TILE,
  },
  {
    id: "init_copper_bit_1",
    x: 12,
    y: 12,
    type: "collectible",
    name: "Copper Bit",
    collectibleType: "copper_bit",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 12 * TILE,
    currPixelY: 12 * TILE,
  },
  {
    id: "init_copper_bit_2",
    x: 14,
    y: 15,
    type: "collectible",
    name: "Copper Bit",
    collectibleType: "copper_bit",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 14 * TILE,
    currPixelY: 15 * TILE,
  },
  {
    id: "init_glow_crystal_1",
    x: 18,
    y: 5,
    type: "collectible",
    name: "Glow Crystal",
    collectibleType: "glow_crystal",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 18 * TILE,
    currPixelY: 5 * TILE,
  },
  {
    id: "init_glow_crystal_2",
    x: 20,
    y: 6,
    type: "collectible",
    name: "Glow Crystal",
    collectibleType: "glow_crystal",
    collectibleState: "idle",
    collectibleTimer: 0,
    currPixelX: 20 * TILE,
    currPixelY: 6 * TILE,
  },
  // ── Mining Nodes ────────────────────────────────────────────────────────────
  {
    id: "node_stone_1",
    x: 10,
    y: 5,
    type: "mining_node",
    name: "Batu",
    miningNodeType: "stone",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_stone_2",
    x: 12,
    y: 6,
    type: "mining_node",
    name: "Batu",
    miningNodeType: "stone",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_stone_3",
    x: 13,
    y: 8,
    type: "mining_node",
    name: "Batu",
    miningNodeType: "stone",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_copper_1",
    x: 11,
    y: 10,
    type: "mining_node",
    name: "Bijih Tembaga",
    miningNodeType: "copper",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_copper_2",
    x: 14,
    y: 11,
    type: "mining_node",
    name: "Bijih Tembaga",
    miningNodeType: "copper",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_copper_3",
    x: 13,
    y: 13,
    type: "mining_node",
    name: "Bijih Tembaga",
    miningNodeType: "copper",
    miningNodeHp: 3,
    miningNodeMaxHp: 3,
    miningNodeRequiredToolLevel: 1,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_crystal_1",
    x: 24,
    y: 5,
    type: "mining_node",
    name: "Kristal Bersinar",
    miningNodeType: "crystal",
    miningNodeHp: 4,
    miningNodeMaxHp: 4,
    miningNodeRequiredToolLevel: 2,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_crystal_2",
    x: 25,
    y: 6,
    type: "mining_node",
    name: "Kristal Bersinar",
    miningNodeType: "crystal",
    miningNodeHp: 4,
    miningNodeMaxHp: 4,
    miningNodeRequiredToolLevel: 2,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_ancient_1",
    x: 11,
    y: 4,
    type: "mining_node",
    name: "Pilar Kuno",
    miningNodeType: "ancient",
    miningNodeHp: 5,
    miningNodeMaxHp: 5,
    miningNodeRequiredToolLevel: 3,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  {
    id: "node_ancient_2",
    x: 15,
    y: 5,
    type: "mining_node",
    name: "Pilar Kuno",
    miningNodeType: "ancient",
    miningNodeHp: 5,
    miningNodeMaxHp: 5,
    miningNodeRequiredToolLevel: 3,
    miningNodeRespawnTimer: 0,
    miningNodeHitTimer: 0,
  },
  // ── Shop & Quest Board ──────────────────────────────────────────────────────
  {
    id: "merchant",
    x: 25,
    y: 11,
    type: "npc",
    name: "Baron the Merchant",
    dialogue: [
      "Halo petualang! Saya Baron si pedagang.",
      "Saya menjual ramuan penyembuh dan jasa peningkatan senjata, serta membeli batu permata!",
      "Gunakan koin yang kamu miliki untuk bertransaksi denganku."
    ],
    dialogueIndex: 0,
    dir: "down",
    moving: false,
    startX: 25,
    startY: 11,
    currPixelX: 25 * TILE,
    currPixelY: 11 * TILE,
    targetX: 25,
    targetY: 11,
    moveCooldown: 0,
  },
  {
    id: "quest_board_village",
    x: 21,
    y: 10,
    type: "quest_board",
    name: "Papan Quest",
    dialogue: ["Membaca Papan Quest Desa..."],
    dialogueIndex: 0,
  },
];
